package com.taf.customListeners;

import com.taf.drivers.UITest;
import com.taf.drivers.WebDriverProvider;
import com.taf.utils.logs.LogsManager;
import com.taf.utils.media.ScreenRecordManager;
import com.taf.utils.media.ScreenshotsManager;
import com.taf.utils.FileUtils;
import com.taf.utils.reporting.AllureAttachmentManager;
import com.taf.utils.reporting.AllureConstants;
import com.taf.utils.reporting.AllureEnvironmentManager;
import com.taf.utils.reporting.AllureReportGenerator;
import com.taf.validations.Validation;
import org.openqa.selenium.WebDriver;
import com.taf.utils.dataReader.PropertyReader;
import org.junit.jupiter.api.extension.*;

import java.io.File;
import java.util.Optional;

/**
 * JUnit 5 Test Listener/Extension for test lifecycle management.
 * This replaces TestNG's IInvokedMethodListener, ITestListener, IExecutionListener, ISuiteListener.
 * =============================================================
 * Usage: Add @ExtendWith(JUnit5TestListener.class) to your test class or configure globally in junit-platform.properties
 */
public class JUnit5TestListener implements
        BeforeAllCallback, AfterAllCallback,
        BeforeEachCallback, AfterEachCallback,
        TestWatcher {

    // Synchronization lock for log file operations in parallel execution
    private static final Object LOG_FILE_LOCK = new Object();
    private static boolean suiteInitialized = false;
    private static final Object SUITE_LOCK = new Object();
    private static boolean shutdownHookRegistered = false;

    // BeforeAll - executed once before all tests
    @Override
    public void beforeAll(ExtensionContext context) throws Exception {
        synchronized (SUITE_LOCK) {
            if (!suiteInitialized) {
                LogsManager.info("Test Execution started");
                PropertyReader.loadProperties();
                LogsManager.info("Properties loaded");
                cleanTestOutputDirectories();
                LogsManager.info("Directories cleaned");
                createTestOutputDirectories();
                LogsManager.info("Directories created");
                AllureEnvironmentManager.setEnvironmentVariables();
                LogsManager.info("Allure environment set");
                suiteInitialized = true;

                // Register shutdown hook ONCE to generate report after ALL tests complete
                registerShutdownHook();
            }
        }
    }

    /**
     * Registers a JVM shutdown hook to generate and open Allure report after ALL tests complete.
     * This ensures the report is only generated once, not after each test class.
     */
    private void registerShutdownHook() {
        synchronized (SUITE_LOCK) {
            if (!shutdownHookRegistered) {
                Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                    try {
                        LogsManager.info("=== Generating Allure Report (Suite Completed) ===");
                        AllureReportGenerator.copyHistory();
                        AllureReportGenerator.generateReports(false);
                        AllureReportGenerator.generateReports(true);
                        AllureReportGenerator.openReport(AllureReportGenerator.renameReport());
                        LogsManager.info("=== Test Execution Finished - Report Opened ===");
                    } catch (Exception e) {
                        LogsManager.error("Failed to generate Allure report in shutdown hook:", e.getMessage());
                    }
                }, "Allure-Report-Generator"));
                shutdownHookRegistered = true;
                LogsManager.info("Shutdown hook registered for Allure report generation");
            }
        }
    }

    // AfterAll - executed after each test class (NOT after entire suite)
    @Override
    public void afterAll(ExtensionContext context) throws Exception {
        // Don't generate report here - it will be generated by shutdown hook after ALL tests
        // This method runs after EACH test class, not after the entire suite
        String className = context.getDisplayName();
        LogsManager.info("Test class completed: " + className);
    }

    // BeforeEach - executed before each test method
    @Override
    public void beforeEach(ExtensionContext context) throws Exception {
        String testMethodName = context.getDisplayName();
        String testDescription = context.getTestMethod()
                .map(m -> m.getName())
                .orElse("Unknown");

        // Synchronize log file clearing to prevent race conditions in parallel execution
        synchronized (LOG_FILE_LOCK) {
            try {
                FileUtils.clearFileContents(LogsManager.LOGS_PATH + "logs.log");
                LogsManager.info("Logs cleared for test:", testMethodName + "/" + testDescription);
            } catch (Exception e) {
                LogsManager.warn("Could not clear log file (may be locked by another thread):", e.getMessage());
            }
        }

        // Check if test instance is UITest for screen recording
        context.getTestInstance().ifPresent(instance -> {
            if (instance instanceof UITest) {
                try {
                    ScreenRecordManager.startRecording();
                } catch (Exception e) {
                    LogsManager.warn("Could not start screen recording:", e.getMessage());
                }
            }
        });

        LogsManager.info("Test Case:", testMethodName + "/" + testDescription, "starting ....");
    }

    // AfterEach - executed after each test method
    @Override
    public void afterEach(ExtensionContext context) throws Exception {
        String testMethodName = context.getDisplayName();
        String testDescription = context.getTestMethod()
                .map(m -> m.getName())
                .orElse("Unknown");
        String fullTestName = testMethodName + "_" + testDescription;

        // Stop recording for UI tests
        context.getTestInstance().ifPresent(instance -> {
            if (instance instanceof UITest) {
                try {
                    ScreenRecordManager.stopRecording(testMethodName);
                } catch (Exception e) {
                    LogsManager.warn("Could not stop screen recording:", e.getMessage());
                }
            }
        });

        try {
            AllureAttachmentManager.attachRecords(testMethodName);
        } catch (Exception e) {
            LogsManager.warn("Could not attach records:", e.getMessage());
        }

        // Assert all soft validations
        Validation.assertAll();
        LogsManager.info("Test Case:", fullTestName, "finished.");

        // Attach logs to allure report
        synchronized (LOG_FILE_LOCK) {
            try {
                File logFile = new File(LogsManager.LOGS_PATH + "logs.log");
                if (logFile.exists()) {
                    AllureAttachmentManager.attachLogs();
                }
            } catch (Exception e) {
                LogsManager.error("Error attaching logs", e.getMessage());
            }
        }
    }

    // TestWatcher methods - for test result tracking
    @Override
    public void testSuccessful(ExtensionContext context) {
        String testName = context.getDisplayName();
        LogsManager.info("Test", testName, "Passed");
    }

    @Override
    public void testFailed(ExtensionContext context, Throwable cause) {
        String testName = context.getDisplayName();
        String testMethodName = context.getTestMethod().map(m -> m.getName()).orElse("Unknown");
        String fullTestName = testName + "_" + testMethodName;

        LogsManager.error("Test", testName, "Failed:", cause.getMessage());

        // Capture screenshot on test failure (runs BEFORE @AfterEach, so driver is still active)
        context.getTestInstance().ifPresent(instance -> {
            if (instance instanceof WebDriverProvider provider) {
                WebDriver driver = provider.getWebDriver();
                if (driver != null) {
                    try {
                        driver.getTitle(); // Verify session is active
                        LogsManager.info("Test failed - capturing screenshot for: " + fullTestName);
                        ScreenshotsManager.takeFullPageScreenshot(driver, "failed-" + fullTestName);
                    } catch (org.openqa.selenium.NoSuchSessionException e) {
                        LogsManager.warn("WebDriver session already closed for thread " +
                                Thread.currentThread().threadId() + ", skipping screenshot");
                    } catch (Exception e) {
                        LogsManager.error("Error taking screenshot:", e.getMessage());
                    }
                } else {
                    LogsManager.debug("Driver is null, skipping screenshot");
                }
            }
        });
    }

    @Override
    public void testAborted(ExtensionContext context, Throwable cause) {
        String testName = context.getDisplayName();
        LogsManager.warn("Test", testName, "Aborted:", cause.getMessage());
    }

    @Override
    public void testDisabled(ExtensionContext context, Optional<String> reason) {
        String testName = context.getDisplayName();
        LogsManager.warn("Test", testName, "Disabled:", reason.orElse("No reason provided"));
    }

    // Utility methods
    private void cleanTestOutputDirectories() {
        FileUtils.cleanDirectory(AllureConstants.RESULTS_FOLDER.toFile());
        FileUtils.cleanDirectory(new File(ScreenshotsManager.SCREENSHOTS_PATH));
        FileUtils.cleanDirectory(new File(ScreenRecordManager.RECORDINGS_PATH));
        FileUtils.cleanDirectory(new File("src/test/resources/downloads/"));
    }

    private void createTestOutputDirectories() {
        FileUtils.createDirectory(ScreenshotsManager.SCREENSHOTS_PATH);
        FileUtils.createDirectory(ScreenRecordManager.RECORDINGS_PATH);
        FileUtils.createDirectory("src/test/resources/downloads/");
    }
}
