#BrowserType > chrome - edge - firefox - safari
browser=chrome
#RemoteExecution > true: Local - false: Remote - false
remoteExecution=true
#Headless Execution > true - false, if remoteExecution is true
headless=true
#Default download folder
downloadFolder=/src/test/resources/downloads/
#Retries Count
retryCount=2
