version: 2.1

# Reusable packages of configuration elements (commands, jobs, executors) that help simplify your CI/CD pipeline setup.
# They're essentially shared libraries for CircleCI configurations.
# https://circleci.com/developer/orbs
orbs:
  maven: circleci/maven@2.1.1
  browser-tools: circleci/browser-tools@2.2.1
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

# The custom executor now directly references the orb's executor
# and then defines any custom settings.
executors:
  windows-edge:
    win/default:
      shell: powershell.exe
      size: medium
      environment:
        EDGE_DRIVER_PATH: "C:/SeleniumWebDrivers/EdgeDriver/msedgedriver.exe"

jobs:
#  chrome-test:
#    docker:
#      - image: cimg/openjdk:21.0.5
#    steps:
#      - checkout
#
#      # Use the browser-tools orb to install Chrome and Chromedriver
#      - browser-tools/install-browser-tools:
#          browser: chrome
#          install-geckodriver: false
#          install-msedgedriver: false
#
#      # The maven orb's test command handles caching and test execution
#      - maven/test:
#          test-command: mvn clean test -Dbrowser=chrome -Dheadless=true -Dtest="%regex[.*Tests.*],com.taf.tests.**.**,com.taf.tests.**"
#          # The maven/test command also handles caching automatically
#
#      # Clean the testng-results.xml file
#      - run:
#          name: Clean test results
#          command: rm -f test-output/target/surefire-reports/testng-results.xml
#
#      # Store the xml test results
#      - store_test_results:
#          path: test-output/target/surefire-reports
#
#      # Store the Allure html report
#      - store_artifacts:
#          path: test-output/reports
#          destination: test-reports
#          when: always
#          retention: 30d

  edge-test:
    executor: windows-edge
    steps:
      - checkout

      # Use the browser-tools orb to install Edge and the Edge driver
      - browser-tools/install-browser-tools:
          browser: msedge
          install-chromedriver: false
          install-geckodriver: false
          install-msedgedriver: true

      # Restore previously cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      # Build the project and download dependencies
      - run:
          name: Build project and download dependencies
          command: mvn dependency:go-offline

      # Creates a new cache of your project's dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Run tests with the provided configuration
      - run:
          name: Run Edge Tests
          command: |
            mvn clean test -Dbrowser=edge -Dheadless=true -Dtest=LoginTest

      # Clean the testng-results.xml file
      - run:
          name: Clean test results
          command: |
            if (Test-Path "test-output\target\surefire-reports\testng-results.xml") {
                Remove-Item "test-output\target\surefire-reports\testng-results.xml"
            }

      # Store the xml test results
      - store_test_results:
          path: test-output/target/surefire-reports

      # Store the Allure html report
      - store_artifacts:
          path: test-output/reports
          destination: test-reports
          when: always
          retention: 30d

workflows:
  version: 2

  on_push:
    jobs:
#      - chrome-test:
#          filters:
#            branches:
#              only:
#                - AutomationExercise
      - edge-test:
          filters:
            branches:
              only:
                - AutomationExercise

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - AutomationExercise
    jobs:
      #- chrome-test
      - edge-test