package com.taf.builders;

import com.taf.utils.TimeManager;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

/**
 * LombokUserData demonstrates the Builder Pattern using Lombok annotations.
 * This is an alternative implementation to UserDataBuilder that uses Lombok's @Builder
 * to automatically generate builder code, reducing boilerplate.
 * ==============================================
 * Key Differences from UserDataBuilder:
 * - Uses Lombok annotations instead of manual builder implementation
 * - Less code to maintain (Lombok generates builder at compile time)
 * - Automatically generates getters, setters, equals, hashCode, toString
 * - Same functionality with ~80% less code
 * ===============================================
 * Design Patterns Applied:
 * - Builder Pattern: Via Lombok's @Builder annotation
 * - Fluent Interface: Automatically generated by Lombok
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LombokUserData {

    private String name;
    private String email;
    private String password;
    private String title;
    private String birthDate;
    private String birthMonth;
    private String birthYear;
    private String firstName;
    private String lastName;
    private String company;
    private String address1;
    private String address2;
    private String country;
    private String zipcode;
    private String state;
    private String city;
    private String mobileNumber;

    // Default values - used by static factory methods
    private static final String[] DEFAULT_TITLES = {"Mr", "Mrs"};
    private static final String[] DEFAULT_MONTHS = {"January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"};
    private static final String[] DEFAULT_COUNTRIES = {"India", "United States", "Canada", "Singapore", "Australia"};
    private static final Random random = new Random();

    /**
     * Create a LombokUserData instance with complete default data.
     * Similar to UserDataBuilder.withCompleteDefaults()
     *
     * @return LombokUserData with complete defaults
     */
    public static LombokUserData withCompleteDefaults() {
        String timestamp = TimeManager.getCompactTimeStamp();
        return LombokUserData.builder()
                .name("TestUser" + timestamp)
                .email("testuser" + timestamp + "@test.com")
                .password("Test@123")
                .title(DEFAULT_TITLES[random.nextInt(DEFAULT_TITLES.length)])
                .birthDate(String.valueOf(1 + random.nextInt(28)))
                .birthMonth(DEFAULT_MONTHS[random.nextInt(DEFAULT_MONTHS.length)])
                .birthYear(String.valueOf(1970 + random.nextInt(30)))
                .firstName("Test")
                .lastName("User")
                .company("Test Company")
                .address1("123 Test Street")
                .address2("Apt 456")
                .country(DEFAULT_COUNTRIES[random.nextInt(DEFAULT_COUNTRIES.length)])
                .zipcode("12345")
                .state("Test State")
                .city("Test City")
                .mobileNumber("1234567890")
                .build();
    }

    /**
     * Create a LombokUserData instance with random data.
     * Similar to UserDataBuilder.withRandomData()
     *
     * @return LombokUserData with random data
     */
    public static LombokUserData withRandomData() {
        String timestamp = TimeManager.getCompactTimeStamp();
        int randomNum = random.nextInt(10000);
        return LombokUserData.builder()
                .name("User" + randomNum)
                .email("user" + timestamp + randomNum + "@test.com")
                .password("Pass" + randomNum + "@123")
                .title(DEFAULT_TITLES[random.nextInt(DEFAULT_TITLES.length)])
                .birthDate(String.valueOf(1 + random.nextInt(28)))
                .birthMonth(DEFAULT_MONTHS[random.nextInt(DEFAULT_MONTHS.length)])
                .birthYear(String.valueOf(1970 + random.nextInt(30)))
                .firstName("FirstName" + randomNum)
                .lastName("LastName" + randomNum)
                .company("Company" + randomNum)
                .address1(randomNum + " Street")
                .address2("Unit " + randomNum)
                .country(DEFAULT_COUNTRIES[random.nextInt(DEFAULT_COUNTRIES.length)])
                .zipcode(String.format("%05d", random.nextInt(100000)))
                .state("State" + randomNum)
                .city("City" + randomNum)
                .mobileNumber(String.format("1%09d", random.nextInt(1000000000)))
                .build();
    }

    /**
     * Convert this LombokUserData instance to a Map for API requests.
     * Similar to UserDataBuilder.buildAsMap()
     *
     * @return Map of field names to values
     */
    public Map<String, String> toMap() {
        Map<String, String> map = new HashMap<>();
        if (name != null) map.put("name", name);
        if (email != null) map.put("email", email);
        if (password != null) map.put("password", password);
        if (title != null) map.put("title", title);
        if (birthDate != null) map.put("birth_date", birthDate);
        if (birthMonth != null) map.put("birth_month", birthMonth);
        if (birthYear != null) map.put("birth_year", birthYear);
        if (firstName != null) map.put("firstname", firstName);
        if (lastName != null) map.put("lastname", lastName);
        if (company != null) map.put("company", company);
        if (address1 != null) map.put("address1", address1);
        if (address2 != null) map.put("address2", address2);
        if (country != null) map.put("country", country);
        if (zipcode != null) map.put("zipcode", zipcode);
        if (state != null) map.put("state", state);
        if (city != null) map.put("city", city);
        if (mobileNumber != null) map.put("mobile_number", mobileNumber);
        return map;
    }

    /**
     * Add unique timestamp to email.
     * Similar to UserDataBuilder.withUniqueEmail()
     *
     * @return This instance with updated email
     */
    public LombokUserData withUniqueEmail() {
        if (this.email != null && !this.email.isEmpty()) {
            String timestamp = TimeManager.getCompactTimeStamp();
            String[] parts = this.email.split("@");
            if (parts.length == 2) {
                this.email = parts[0] + timestamp + "@" + parts[1];
            } else {
                this.email = this.email + timestamp;
            }
        }
        return this;
    }
}
